### ISSUE TITLE
Data Caching & Refresh

### ISSUE THREAD

**Issue by viktor-bd** [viktor-bd/viktor-bd.github.io#6]
**Feature:** Data Caching & Refresh  
**User Story Title:** Cache Gas Data & Prices  
**Acceptance Criteria:**  
- Gas compositions and ISK prices are cached in Postgres.  
- Prices refresh on schedule or on-demand.  
- Stale data is flagged or automatically updated.  
**Complexity:** High  
**Dependencies:** Yield Dashboard, Profile Management

**Comment by viktor-bd** [comment]
## Design Document: Data Caching & Refresh

### Overview
This document outlines the implementation plan for caching gas data and ISK prices in SQL Server, with scheduled and on-demand refresh capabilities.

---

## 1. Database Schema & Migrations

### New NuGet Packages Required
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" />
```

### Entity Models

**GasType.cs**
```csharp
public class GasType
{
    [Key]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;
    
    [Column(TypeName = "decimal(18,2)")]
    public decimal CurrentIskPerM3 { get; set; }
    
    public DateTime LastUpdated { get; set; }
    
    public bool IsStale => DateTime.UtcNow - LastUpdated > TimeSpan.FromHours(6);
    
    // Navigation
    public ICollection<GasPriceHistory> PriceHistory { get; set; } = [];
    public ICollection<GasCloud> Clouds { get; set; } = [];
}
```

**GasCloud.cs**
```csharp
public class GasCloud
{
    [Key]
    public int Id { get; set; }
    
    [MaxLength(10)]
    public string SigId { get; set; } = string.Empty;
    
    [MaxLength(100)]
    public string SiteName { get; set; } = string.Empty;
    
    [MaxLength(100)]
    public string GasTypeName { get; set; } = string.Empty;
    
    [Column(TypeName = "decimal(18,2)")]
    public decimal VolumeM3 { get; set; }
    
    // Navigation
    public GasType? GasType { get; set; }
}
```

**GasPriceHistory.cs**
```csharp
public class GasPriceHistory
{
    [Key]
    public int Id { get; set; }
    
    [MaxLength(100)]
    public string GasTypeName { get; set; } = string.Empty;
    
    [Column(TypeName = "decimal(18,2)")]
    public decimal IskPerM3 { get; set; }
    
    public DateTime RetrievedAt { get; set; }
    
    [MaxLength(50)]
    public string Source { get; set; } = string.Empty; // "manual", "esi", "fuzzwork", etc.
    
    // Navigation
    public GasType? GasType { get; set; }
}
```

**UserProfile.cs** (migrate from localStorage)
```csharp
public class UserProfile
{
    [Key]
    public int ProfileId { get; set; }
    
    [MaxLength(100)]
    public string CharacterName { get; set; } = string.Empty;
    
    [Column(TypeName = "decimal(8,2)")]
    public decimal HuffRateBase { get; set; } // m3/s base rate
    
    [Column(TypeName = "decimal(5,4)")]
    public decimal LinkBonus { get; set; } // e.g., 0.15 = 15% boost
    
    [Column(TypeName = "decimal(5,4)")]
    public decimal ModuleBonus { get; set; }
    
    [Column(TypeName = "decimal(5,4)")]
    public decimal ImplantBonus { get; set; }
    
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
```

### DbContext
```csharp
public class CloudHufferDbContext : DbContext
{
    public CloudHufferDbContext(DbContextOptions<CloudHufferDbContext> options) 
        : base(options) { }
    
    public DbSet<GasType> GasTypes => Set<GasType>();
    public DbSet<GasCloud> GasClouds => Set<GasCloud>();
    public DbSet<GasPriceHistory> GasPriceHistory => Set<GasPriceHistory>();
    public DbSet<UserProfile> UserProfiles => Set<UserProfile>();
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // GasType -> GasCloud (1:N)
        modelBuilder.Entity<GasCloud>()
            .HasOne(c => c.GasType)
            .WithMany(g => g.Clouds)
            .HasForeignKey(c => c.GasTypeName);
        
        // GasType -> PriceHistory (1:N)
        modelBuilder.Entity<GasPriceHistory>()
            .HasOne(h => h.GasType)
            .WithMany(g => g.PriceHistory)
            .HasForeignKey(h => h.GasTypeName);
        
        // Index for price history queries
        modelBuilder.Entity<GasPriceHistory>()
            .HasIndex(h => new { h.GasTypeName, h.RetrievedAt });
        
        // Seed static gas composition data
        SeedGasTypes(modelBuilder);
    }
    
    private static void SeedGasTypes(ModelBuilder modelBuilder)
    {
        // Seed from existing hardcoded data in probe-parser.component.ts
        modelBuilder.Entity<GasType>().HasData(
            new GasType { Name = "Fullerite-C50", CurrentIskPerM3 = 0, LastUpdated = DateTime.MinValue },
            new GasType { Name = "Fullerite-C60", CurrentIskPerM3 = 0, LastUpdated = DateTime.MinValue }
            // ... add all gas types from GasCloudTable.md
        );
    }
}
```

### Migration Commands
```bash
# Add EF tools if not present
dotnet tool install --global dotnet-ef

# Create initial migration
dotnet ef migrations add InitialCreate -p CloudHufferApi -o Data/Migrations

# Apply migration
dotnet ef database update -p CloudHufferApi
```

---

## 2. Docker Configuration

**docker-compose.yml**
```yaml
version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudhuffer-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD:-CloudHuffer123!}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" -C
      interval: 10s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: cloudhuffer-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: CloudHufferApi/Dockerfile
    container_name: cloudhuffer-api
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5161:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CloudHuffer;User=sa;Password=${SQL_PASSWORD:-CloudHuffer123!};TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - PriceRefresh__IntervalHours=6
      - PriceRefresh__StaleThresholdHours=12

volumes:
  sqlserver-data:
  redis-data:
```

---

## 3. API Changes

### New Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| GET | `/api/prices` | Get all current gas prices |
| GET | `/api/prices/{gasType}` | Get price for specific gas |
| GET | `/api/prices/{gasType}/history` | Get price history |
| POST | `/api/prices/refresh` | Trigger on-demand refresh |
| GET | `/api/prices/status` | Cache status & staleness info |

### DTOs

```csharp
public record GasPriceDto(
    string GasType,
    decimal IskPerM3,
    DateTime LastUpdated,
    bool IsStale
);

public record PriceStatusDto(
    DateTime LastRefresh,
    DateTime NextScheduledRefresh,
    int TotalGasTypes,
    int StaleCount,
    List<string> StaleGasTypes
);

public record PriceHistoryDto(
    string GasType,
    List<PricePointDto> History
);

public record PricePointDto(
    decimal IskPerM3,
    DateTime RetrievedAt,
    string Source
);
```

### Controller

```csharp
[ApiController]
[Route("api/[controller]")]
public class PricesController : ControllerBase
{
    private readonly IPriceService _priceService;
    private readonly IPriceCacheService _cacheService;
    
    [HttpGet]
    public async Task<ActionResult<List<GasPriceDto>>> GetAllPrices()
    {
        var prices = await _cacheService.GetOrFetchPricesAsync();
        return Ok(prices);
    }
    
    [HttpGet("{gasType}")]
    public async Task<ActionResult<GasPriceDto>> GetPrice(string gasType)
    {
        var price = await _cacheService.GetPriceAsync(gasType);
        return price is null ? NotFound() : Ok(price);
    }
    
    [HttpGet("{gasType}/history")]
    public async Task<ActionResult<PriceHistoryDto>> GetPriceHistory(
        string gasType, 
        [FromQuery] int days = 30)
    {
        var history = await _priceService.GetPriceHistoryAsync(gasType, days);
        return Ok(history);
    }
    
    [HttpPost("refresh")]
    public async Task<ActionResult<PriceStatusDto>> RefreshPrices()
    {
        await _priceService.RefreshAllPricesAsync();
        var status = await _priceService.GetStatusAsync();
        return Ok(status);
    }
    
    [HttpGet("status")]
    public async Task<ActionResult<PriceStatusDto>> GetStatus()
    {
        var status = await _priceService.GetStatusAsync();
        return Ok(status);
    }
}
```

---

## 4. Caching Strategy

### Multi-Layer Cache Architecture

```
+----------------------------------------------------------+
|                    Angular Frontend                       |
|  +----------------------------------------------------+  |
|  |  In-Memory Cache (BehaviorSubject, 5 min TTL)      |  |
|  +----------------------------------------------------+  |
+----------------------------------------------------------+
                           |
                           v
+----------------------------------------------------------+
|                   .NET Core API                           |
|  +----------------------------------------------------+  |
|  |  Redis Cache (IDistributedCache, 1 hour TTL)       |  |
|  +----------------------------------------------------+  |
|  +----------------------------------------------------+  |
|  |  SQL Server (Source of Truth)                      |  |
|  +----------------------------------------------------+  |
+----------------------------------------------------------+
                           |
                           v
+----------------------------------------------------------+
|  External Price API (Fuzzwork / EVEMarketer)              |
|  - Called on schedule (every 6 hours)                     |
|  - Or on-demand via POST /api/prices/refresh              |
+----------------------------------------------------------+
```

### Cache Service Implementation

```csharp
public interface IPriceCacheService
{
    Task<List<GasPriceDto>> GetOrFetchPricesAsync();
    Task<GasPriceDto?> GetPriceAsync(string gasType);
    Task InvalidateCacheAsync();
}

public class PriceCacheService : IPriceCacheService
{
    private readonly IDistributedCache _cache;
    private readonly IPriceRepository _repository;
    private readonly ILogger<PriceCacheService> _logger;
    
    private const string CacheKey = "gas_prices_all";
    private static readonly TimeSpan CacheDuration = TimeSpan.FromHours(1);
    
    public async Task<List<GasPriceDto>> GetOrFetchPricesAsync()
    {
        // Try Redis first
        var cached = await _cache.GetStringAsync(CacheKey);
        if (cached is not null)
        {
            return JsonSerializer.Deserialize<List<GasPriceDto>>(cached)!;
        }
        
        // Fallback to SQL Server
        var prices = await _repository.GetAllPricesAsync();
        
        // Populate cache
        await _cache.SetStringAsync(
            CacheKey,
            JsonSerializer.Serialize(prices),
            new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = CacheDuration
            });
        
        return prices;
    }
}
```

### Scheduled Background Service

```csharp
public class PriceRefreshBackgroundService : BackgroundService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<PriceRefreshBackgroundService> _logger;
    private readonly TimeSpan _interval;
    
    public PriceRefreshBackgroundService(
        IServiceProvider serviceProvider,
        IConfiguration config,
        ILogger<PriceRefreshBackgroundService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
        _interval = TimeSpan.FromHours(
            config.GetValue<int>("PriceRefresh:IntervalHours", 6));
    }
    
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                using var scope = _serviceProvider.CreateScope();
                var priceService = scope.ServiceProvider
                    .GetRequiredService<IPriceService>();
                
                _logger.LogInformation("Starting scheduled price refresh");
                await priceService.RefreshAllPricesAsync();
                _logger.LogInformation("Price refresh completed");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Price refresh failed");
            }
            
            await Task.Delay(_interval, stoppingToken);
        }
    }
}
```

### Staleness Detection

```csharp
public class PriceService : IPriceService
{
    private readonly TimeSpan _staleThreshold;
    
    public async Task<PriceStatusDto> GetStatusAsync()
    {
        var prices = await _repository.GetAllPricesAsync();
        var staleItems = prices.Where(p => p.IsStale).ToList();
        
        return new PriceStatusDto(
            LastRefresh: prices.Max(p => p.LastUpdated),
            NextScheduledRefresh: CalculateNextRefresh(),
            TotalGasTypes: prices.Count,
            StaleCount: staleItems.Count,
            StaleGasTypes: staleItems.Select(p => p.GasType).ToList()
        );
    }
}
```

---

## 5. External Price API Integration

### Price Provider Interface

```csharp
public interface IPriceProvider
{
    string Name { get; }
    Task<Dictionary<string, decimal>> FetchPricesAsync(IEnumerable<int> typeIds);
}

// Fuzzwork API implementation (https://market.fuzzwork.co.uk/api/)
public class FuzzworkPriceProvider : IPriceProvider
{
    private readonly HttpClient _httpClient;
    
    public string Name => "fuzzwork";
    
    public async Task<Dictionary<string, decimal>> FetchPricesAsync(
        IEnumerable<int> typeIds)
    {
        var ids = string.Join(",", typeIds);
        var url = $"https://market.fuzzwork.co.uk/aggregates/?station=60003760&types={ids}";
        
        var response = await _httpClient.GetFromJsonAsync<
            Dictionary<string, FuzzworkPriceData>>(url);
        
        return response?.ToDictionary(
            kvp => kvp.Key,
            kvp => kvp.Value.Buy.Max) ?? [];
    }
}
```

### Gas Type ID Mapping

```csharp
public static class GasTypeIds
{
    // EVE Online Type IDs for gas clouds
    public static readonly Dictionary<string, int> TypeIds = new()
    {
        ["Fullerite-C50"] = 30370,
        ["Fullerite-C60"] = 30371,
        ["Fullerite-C70"] = 30372,
        ["Fullerite-C72"] = 30373,
        ["Fullerite-C84"] = 30374,
        ["Fullerite-C320"] = 30375,
        ["Fullerite-C540"] = 30376,
        // ... add remaining gas types
    };
}
```

---

## 6. Implementation Plan

| Phase | Tasks | Estimate |
|-------|-------|----------|
| **Phase 1** | Add EF Core + SQL Server, create migrations, docker-compose | 4-6 hours |
| **Phase 2** | Implement PriceRepository + PriceCacheService | 3-4 hours |
| **Phase 3** | Add Redis integration + background service | 2-3 hours |
| **Phase 4** | Integrate external price API (Fuzzwork) | 2-3 hours |
| **Phase 5** | Add API endpoints + frontend integration | 3-4 hours |
| **Phase 6** | Testing + documentation | 2-3 hours |

**Total Estimate:** 16-23 hours

---

## 7. Configuration

**appsettings.json**
```json
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=localhost;Database=CloudHuffer;Trusted_Connection=true;TrustServerCertificate=true",
    "Redis": "localhost:6379"
  },
  "PriceRefresh": {
    "IntervalHours": 6,
    "StaleThresholdHours": 12,
    "Provider": "fuzzwork",
    "FallbackProvider": "evemarketer"
  }
}
```

---

## 8. Success Criteria

- [ ] Gas prices stored in SQL Server with timestamp
- [ ] Redis cache reduces DB queries by >90%
- [ ] Background job runs every 6 hours without intervention
- [ ] POST /api/prices/refresh completes in <30 seconds
- [ ] Stale data (>12 hours old) is flagged in UI
- [ ] Price history retained for trend analysis

---

## Questions / Decisions Needed

1. **Price source preference**: Fuzzwork vs EVEMarketer vs Janice?
2. **History retention**: How many days of price history to keep?
3. **Stale threshold**: 12 hours proposed - acceptable?
4. **User profiles**: Migrate from localStorage to SQL, or keep hybrid?

---

*Generated for Issue #6 - Data Caching & Refresh*

**Comment by viktor-bd** [comment]
## Design Update: PostgreSQL Instead of SQL Server

Per discussion, updating the design to use **PostgreSQL** instead of SQL Server.

---

### Changes Summary

#### 1. NuGet Packages

**Before (SQL Server):**
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
```

**After (PostgreSQL):**
```xml
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
```

---

#### 2. Docker Compose

**Replace `sqlserver` service with:**
```yaml
services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudhuffer-db
    environment:
      - POSTGRES_USER=cloudhuffer
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CloudHuffer123!}
      - POSTGRES_DB=cloudhuffer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudhuffer -d cloudhuffer"]
      interval: 10s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: cloudhuffer-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: CloudHufferApi/Dockerfile
    container_name: cloudhuffer-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5161:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=cloudhuffer;Username=cloudhuffer;Password=${POSTGRES_PASSWORD:-CloudHuffer123!}
      - ConnectionStrings__Redis=redis:6379
      - PriceRefresh__IntervalHours=6
      - PriceRefresh__StaleThresholdHours=12

volumes:
  postgres-data:
  redis-data:
```

---

#### 3. Connection String

**appsettings.json:**
```json
{
  "ConnectionStrings": {
    "DefaultConnection": "Host=localhost;Database=cloudhuffer;Username=cloudhuffer;Password=CloudHuffer123!",
    "Redis": "localhost:6379"
  }
}
```

**appsettings.Development.json:**
```json
{
  "ConnectionStrings": {
    "DefaultConnection": "Host=localhost;Port=5432;Database=cloudhuffer;Username=cloudhuffer;Password=CloudHuffer123!"
  }
}
```

---

#### 4. Program.cs Configuration

```csharp
builder.Services.AddDbContext<CloudHufferDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));
```

---

#### 5. Entity Model Adjustments

PostgreSQL uses different column type conventions. Minor updates:

```csharp
// decimal columns - PostgreSQL uses 'numeric' type (EF Core handles this automatically)
[Column(TypeName = "numeric(18,2)")]
public decimal CurrentIskPerM3 { get; set; }

// DateTime - PostgreSQL uses 'timestamp with time zone'
// No attribute needed; Npgsql handles DateTime/DateTimeOffset automatically
public DateTime LastUpdated { get; set; }
```

---

#### 6. Benefits of PostgreSQL

| Aspect | PostgreSQL | SQL Server |
|--------|------------|------------|
| **Licensing** | Free & open source | Developer edition free, production requires license |
| **Container size** | ~80MB (alpine) | ~1.5GB |
| **Memory footprint** | Lower baseline | Higher baseline |
| **Cross-platform** | Native Linux/macOS/Windows | Best on Windows |
| **JSON support** | Native JSONB type | JSON functions available |
| **Community** | Large open-source community | Enterprise-focused |

---

### No Other Changes Required

The rest of the design remains the same:
- Entity models (GasType, GasCloud, GasPriceHistory, UserProfile)
- DbContext structure and relationships
- API endpoints and DTOs
- Caching strategy (Redis + in-memory)
- Background service for scheduled refresh
- External price API integration

---

*Updated for Issue #6 - Data Caching & Refresh*

**Comment by viktor-bd** [comment]
## Design Update v2: Simplified Architecture (No Redis)

Based on review, simplifying the design:
- **Removed Redis** - premature optimization for current scale
- **Clarified expiration logic** - TTL-based staleness check on request

---

## Revised Architecture

```
+----------------------------------------------------------+
|                    Angular Frontend                       |
|  +----------------------------------------------------+  |
|  |  In-Memory Cache (BehaviorSubject, 5 min TTL)      |  |
|  +----------------------------------------------------+  |
+----------------------------------------------------------+
                           |
                           v
+----------------------------------------------------------+
|                   .NET Core API                           |
|  +----------------------------------------------------+  |
|  |  IMemoryCache (optional, for hot path)             |  |
|  +----------------------------------------------------+  |
|  +----------------------------------------------------+  |
|  |  PostgreSQL (Source of Truth)                      |  |
|  +----------------------------------------------------+  |
+----------------------------------------------------------+
                           |
                           v
+----------------------------------------------------------+
|  External Price API (Fuzzwork)                            |
|  - Called when data is stale (lazy refresh)               |
|  - Or on-demand via POST /api/prices/refresh              |
+----------------------------------------------------------+
```

---

## Expiration Strategy: Lazy Refresh on Request

Instead of a background service polling every 6 hours, use **lazy evaluation**:

### How It Works

1. User requests prices via `GET /api/prices`
2. API checks `LastUpdated` timestamp in database
3. If `DateTime.UtcNow - LastUpdated > ExpirationThreshold` → data is stale
4. If stale: fetch fresh prices from external API, update DB, return fresh data
5. If fresh: return cached data from DB

### Benefits
- No background services to manage
- No Redis infrastructure
- Prices only refresh when actually needed
- First request after expiry is slower, but subsequent requests are fast

### Configuration

```json
{
  "PriceSettings": {
    "ExpirationHours": 2,
    "StaleWarningHours": 1.5
  }
}
```

---

## Updated Code

### PriceSettings.cs
```csharp
public class PriceSettings
{
    public double ExpirationHours { get; set; } = 2.0;
    public double StaleWarningHours { get; set; } = 1.5;
    
    public TimeSpan Expiration => TimeSpan.FromHours(ExpirationHours);
    public TimeSpan StaleWarning => TimeSpan.FromHours(StaleWarningHours);
}
```

### IPriceService.cs
```csharp
public interface IPriceService
{
    Task<List<GasPriceDto>> GetPricesAsync(bool forceRefresh = false);
    Task<GasPriceDto?> GetPriceAsync(string gasType);
    Task<PriceStatusDto> GetStatusAsync();
    Task RefreshPricesAsync();
}
```

### PriceService.cs
```csharp
public class PriceService : IPriceService
{
    private readonly CloudHufferDbContext _db;
    private readonly IPriceProvider _priceProvider;
    private readonly PriceSettings _settings;
    private readonly ILogger<PriceService> _logger;
    
    public async Task<List<GasPriceDto>> GetPricesAsync(bool forceRefresh = false)
    {
        var prices = await _db.GasTypes.ToListAsync();
        
        // Check if any price is expired
        var now = DateTime.UtcNow;
        var oldestUpdate = prices.Min(p => p.LastUpdated);
        var isExpired = (now - oldestUpdate) > _settings.Expiration;
        
        if (forceRefresh || isExpired)
        {
            _logger.LogInformation(
                "Prices expired (oldest: {Age} hours). Refreshing...", 
                (now - oldestUpdate).TotalHours);
            
            await RefreshPricesAsync();
            prices = await _db.GasTypes.ToListAsync();
        }
        
        return prices.Select(p => new GasPriceDto(
            GasType: p.Name,
            IskPerM3: p.CurrentIskPerM3,
            LastUpdated: p.LastUpdated,
            IsStale: (now - p.LastUpdated) > _settings.StaleWarning,
            IsExpired: (now - p.LastUpdated) > _settings.Expiration
        )).ToList();
    }
    
    public async Task RefreshPricesAsync()
    {
        try
        {
            var freshPrices = await _priceProvider.FetchPricesAsync();
            var now = DateTime.UtcNow;
            
            foreach (var (gasType, price) in freshPrices)
            {
                var entity = await _db.GasTypes.FindAsync(gasType);
                if (entity is not null)
                {
                    // Store history before updating
                    _db.GasPriceHistory.Add(new GasPriceHistory
                    {
                        GasTypeName = gasType,
                        IskPerM3 = price,
                        RetrievedAt = now,
                        Source = _priceProvider.Name
                    });
                    
                    entity.CurrentIskPerM3 = price;
                    entity.LastUpdated = now;
                }
            }
            
            await _db.SaveChangesAsync();
            _logger.LogInformation("Refreshed {Count} gas prices", freshPrices.Count);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to refresh prices from external API");
            throw; // Let controller handle graceful degradation
        }
    }
}
```

### Updated DTO
```csharp
public record GasPriceDto(
    string GasType,
    decimal IskPerM3,
    DateTime LastUpdated,
    bool IsStale,      // Warning: approaching expiration
    bool IsExpired     // Actually expired, refresh triggered
);
```

### Controller with Graceful Degradation
```csharp
[HttpGet]
public async Task<ActionResult<PriceResponse>> GetAllPrices(
    [FromQuery] bool forceRefresh = false)
{
    try
    {
        var prices = await _priceService.GetPricesAsync(forceRefresh);
        return Ok(new PriceResponse(prices, RefreshStatus: "ok"));
    }
    catch (HttpRequestException)
    {
        // External API failed - return stale data with warning
        var stalePrices = await _priceService.GetCachedPricesAsync();
        return Ok(new PriceResponse(stalePrices, RefreshStatus: "external_api_unavailable"));
    }
}

public record PriceResponse(
    List<GasPriceDto> Prices,
    string RefreshStatus  // "ok", "external_api_unavailable", "refresh_in_progress"
);
```

---

## Revised Docker Compose (No Redis)

```yaml
version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudhuffer-db
    environment:
      - POSTGRES_USER=cloudhuffer
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ChangeMeInProd!}
      - POSTGRES_DB=cloudhuffer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudhuffer -d cloudhuffer"]
      interval: 10s
      retries: 10
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: CloudHufferApi/Dockerfile
    container_name: cloudhuffer-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5161:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=cloudhuffer;Username=cloudhuffer;Password=${POSTGRES_PASSWORD:-ChangeMeInProd!}
      - PriceSettings__ExpirationHours=2
      - PriceSettings__StaleWarningHours=1.5

volumes:
  postgres-data:
```

---

## Trade-offs of This Approach

| Aspect | Lazy Refresh | Background Service |
|--------|--------------|-------------------|
| First request after expiry | Slower (~1-2s) | Always fast |
| Infrastructure complexity | Lower | Higher |
| Resource usage | On-demand only | Constant polling |
| Debugging | Simpler | More moving parts |
| Offline resilience | Same (DB is source of truth) | Same |

**Recommendation:** Start with lazy refresh. Add background service later if users complain about the occasional slow reque
